version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.development
    volumes:
      - .:/app
    ports:
      - '27081:80'
    container_name: wxcloud_qianmian
    labels:
      - wxPort=27082
      - hostPort=27081
      - wxcloud=qianmian
      - role=container
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_PASSWORD=Cyx4161753!
      - MYSQL_ADDRESS=10.29.103.86:3306

networks:
  default:
    external:
      name: wxcb0
